project:
  type: book
  output-dir: _book

book:
  title: "Cyber2A: AI for Arctic Research"
  author: "Wenwen Li, Anna Liljedahl, Matthew B. Jones, Chia-Yu Hsu, Alyona Kosobokova, Jim Regetz, Chandi Witharana, Yili Yang, Ben Galewsky, Minu Mathew, Sandeep Satheesan, Nicole Greco, Kenton McHenry, Carmen Galaz García, Kate Holman Billmeier"
  date: "2024-10-21"
  search: true
  favicon: images/index/arcticlogo.png
  chapters:
    - index.qmd
    - part: "<b>Day 1: Introduction to AI and Arctic Science</b>"
      chapters:
        - sections/breaking-the-ice-with-ai-in-arctic-science.qmd
        - sections/ai-for-everyone.qmd
        - sections/ai-ready-data-in-arctic-research.qmd
        - sections/data-annotation.qmd
        - sections/hands-on-lab-data-annotation.qmd    
    
    - part: "<b>Day 2: AI Fundamentals and Techniques</b>"
      chapters:
        - sections/the-building-blocks-of-nn-and-dl.qmd
        - sections/intro-to-pytorch.qmd
        - sections/hands-on-lab-pytorch.qmd
        - sections/permafrost-discovery-gateway.qmd
        - sections/ai-ethics.qmd

    - part: "<b>Day 3: Advanced AI Workflows and Models</b>"
      chapters:
        - sections/guest-lecture-yili-arts-dataset.qmd
        - sections/exploring-advanced-neural-networks.qmd
        - sections/intro-to-dl-libraries-for-image-analysis.qmd
        - sections/hands-on-lab-mmsegmentation.qmd

    - part: "<b>Day 4: Workflows and Foundation Models</b>"
      chapters:
        - sections/ai-workflows-and-mlops.qmd
        - sections/hands-on-lab-ai-workflows.qmd
        - sections/foundation-models.qmd
        - sections/hands-on-lab-foundation-models.qmd
        - sections/reproducibility.qmd
    
    - part: "<b>Day 5: AI Frontiers</b>"
      chapters:
        - sections/the-fun-and-frontiers-of-ai.qmd
    - references.qmd

    
  sidebar:
    tools:
      - icon: house-door-fill
        href: https://cyber2a.github.io
        aria-label: Cyber2A Homepage
      - icon: twitter
        href: https://twitter.com/cyber2a_nsf
        aria-label: Twitter
      - icon: github
        href: https://github.com/cyber2a/cyber2a-course
        aria-label: GitHub

bibliography: references.bib
csl: ieee.csl

format:
  html:
    theme: cosmo



