# Workshop Development Guidelines {.unnumbered}

These guidelines are here to help you create effective and engaging sessions for our workshop. The goal is to balance theory with practical work, making the learning experience enjoyable and easy to follow.

## Session Structure and Content

* **Balance Theory and Hands-On Work:** Spend about one-third of the time on theory and the other two-thirds on hands-on activities.

* **Build Gradually:** Start with the basics and build up gradually. Expand both the theory and hands-on tasks as you go along. For example, This [Jupyter notebook](https://github.com/NCEAS/scalable-computing-examples/blob/main/04-pleasing/pleasing.ipynb) from NCEAS workshop shows how to introduce theory and hands-on practice.  

* **Choose Your Tools:** You can use either Jupyter Notebook or VSCode for the hands-on parts of your session. Choose whichever one you’re more comfortable with. We will be using [CyVerse Learning Center](https://learning.cyverse.org) for the hands-on part of the workshop.

* **Check Data Licensing:** If you are using any data in your session, ensure that you check the data license to confirm that it can be used and shared freely, both within the workshop and when the course materials are later open-sourced.

* **Offer Support:** Make sure participants know how to ask for help if they get stuck. Regularly ask participants if they’re keeping up and adjust your pace if needed.

* **Extra Resources:** Provide additional materials like readings or videos for participants who want to learn more.

## Editing Session Materials

We are using [Quarto](https://quarto.org) to create the workshop materials. You can find the source files for the workshop materials at [GitHub](https://github.com/cyber2a/cyber2a-course). The pages for each session have already been established, and you just need to add your content to the corresponding session file. The content is primarily written in Markdown, with some additional features provided by Quarto. Here are some tips for editing the materials:

* **Getting Started**: You can find a guide to getting started with Quarto, including editing and previewing your content locally with various tools, [here](https://quarto.org/docs/get-started/).

* **Quarto Guide:** You can find a comprehensive guide to Quarto [here](https://quarto.org/docs/guide/).

* **Format**: You can choose to write your content in either Jupyter Notebook (`.ipynb`) or Markdown files (`.qmd`). Quarto can render both formats.

* **Embed Notebooks**: If you choose to write your content in Markdown but have a separate Jupyter Notebook for the hands-on part, you can embed the notebook. Follow the guide [here](https://quarto.org/docs/computations/python.html#embed-notebooks) to learn how to do this. 

If you have any questions or need help with editing the materials, please reach out to [Chia-Yu Hsu](mailto: chsu53@asu.edu) or ask in the Slack channel.
